# Generated by packaging/render.sh. Do not edit by hand.
class Snob < Formula
  desc "Instagram CLI client with extra utilities, media downloads and output ready for AI agents"
  homepage "https://github.com/dennisgr7/snob-cli"
  version "0.5.0"
  license "MIT"

  on_macos do
    # There is no macOS Intel build; see the note in .github/workflows/ci.yml.
    depends_on arch: :arm64
    url "https://github.com/dennisgr7/snob-cli/releases/download/v0.5.0/snob-v0.5.0-aarch64-apple-darwin.tar.gz"
    sha256 "917d20553f20d7bac02b4a5f3d37b5c96e394b620ad491964221e912bcf78433"
  end

  on_linux do
    on_intel do
      url "https://github.com/dennisgr7/snob-cli/releases/download/v0.5.0/snob-v0.5.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "bf2015638381c3a91f215ee0c180f91d721bcd0a6474d9ecf7c65acbfaadffec"
    end
    on_arm do
      url "https://github.com/dennisgr7/snob-cli/releases/download/v0.5.0/snob-v0.5.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "cdabe60ed2e4945e625669475368aad8c95d567adbaeb0030e14c8c4fcf10616"
    end
  end

  def install
    bin.install "snob"
  end

  def caveats
    <<~CAVEATS
      snob keeps a session, a database and browser profiles outside this
      prefix, which uninstalling cannot reach. Run "snob purge" before
      removing it to take those off the machine too.
    CAVEATS
  end

  test do
    assert_match "snob #{version}", shell_output("#{bin}/snob --version")
  end
end
