# Generated by packaging/render.sh. Do not edit by hand.
class Snob < Formula
  desc "Instagram CLI client with extra utilities, media downloads and output ready for AI agents"
  homepage "https://github.com/dennisgr7/snob-cli"
  version "0.7.0"
  license "MIT"

  on_macos do
    # There is no macOS Intel build; see the note in .github/workflows/ci.yml.
    depends_on arch: :arm64
    url "https://github.com/dennisgr7/snob-cli/releases/download/v0.7.0/snob-v0.7.0-aarch64-apple-darwin.tar.gz"
    sha256 "63e6d60e48980635f103e2431fa5e2239c04cce973cc96852ca97c96b6b8b0fa"
  end

  on_linux do
    on_intel do
      url "https://github.com/dennisgr7/snob-cli/releases/download/v0.7.0/snob-v0.7.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "b3297639e49bab3324d7f2a43ad754b2df515753fd4eb350148e16e4f59fa4c1"
    end
    on_arm do
      url "https://github.com/dennisgr7/snob-cli/releases/download/v0.7.0/snob-v0.7.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "43073e36a906e80cd6b28a00ad884450a523449a889b2171cc1321ca3768126f"
    end
  end

  def install
    bin.install "snob"
  end

  def caveats
    <<~CAVEATS
      snob keeps a session, a database and browser profiles outside this
      prefix, which uninstalling cannot reach. Run "snob purge" before
      removing it to take those off the machine too.
    CAVEATS
  end

  test do
    assert_match "snob #{version}", shell_output("#{bin}/snob --version")
  end
end
