# Generated by packaging/render.sh. Do not edit by hand.
class Snob < Formula
  desc "Instagram CLI client with extra utilities, media downloads and output ready for AI agents"
  homepage "https://github.com/dennisgr7/snob-cli"
  version "0.6.0"
  license "MIT"

  on_macos do
    # There is no macOS Intel build; see the note in .github/workflows/ci.yml.
    depends_on arch: :arm64
    url "https://github.com/dennisgr7/snob-cli/releases/download/v0.6.0/snob-v0.6.0-aarch64-apple-darwin.tar.gz"
    sha256 "a96edc9742ce27bfc31dd1f3a90e82d2c53ebb8d1a1391d99e4b54618c1467d0"
  end

  on_linux do
    on_intel do
      url "https://github.com/dennisgr7/snob-cli/releases/download/v0.6.0/snob-v0.6.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "49ecc2c79a127a9ce5d56e205c703c5ee96d53c7d8653255659381d46e6d07e4"
    end
    on_arm do
      url "https://github.com/dennisgr7/snob-cli/releases/download/v0.6.0/snob-v0.6.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "62b4d52cbe8220f2d5a5094e7daeeb74ea0b3b97228bc45530aa85a7e6ea1f1a"
    end
  end

  def install
    bin.install "snob"
  end

  def caveats
    <<~CAVEATS
      snob keeps a session, a database and browser profiles outside this
      prefix, which uninstalling cannot reach. Run "snob purge" before
      removing it to take those off the machine too.
    CAVEATS
  end

  test do
    assert_match "snob #{version}", shell_output("#{bin}/snob --version")
  end
end
